version: '3'

services:
    runner_jupyter:
      build: .
      working_dir: /app      
      volumes:
        - .:/app
      ports:
        - 8888:8888
      command: jupyter notebook --ip 0.0.0.0 --allow-root